import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('scripts/art/evidence', { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
await page.goto(`${process.env.ART_PREVIEW_URL ?? 'http://127.0.0.1:5189'}/scripts/art/preview.html`);
await page.waitForFunction(() => window.artReady, undefined, { timeout: 30000 });
await page.waitForTimeout(1000);
await page.screenshot({ path: 'scripts/art/evidence/island-before.png' });
const metrics = { closed: await page.evaluate(() => window.artInfo) };
await page.evaluate(() => window.setArtState({ logRolled: true }));
await page.waitForTimeout(1500);
await page.screenshot({ path: 'scripts/art/evidence/bridge-unrooted.png' });
await page.evaluate(() => window.setArtState({ leafGrown: true }));
await page.waitForTimeout(1500);
await page.screenshot({ path: 'scripts/art/evidence/leaf-grown.png' });
await page.evaluate(() => window.setArtState({ logRolled: true, bridge: true, bloom: true, gate: true, leafGrown: true, leafLaunched: true, campKeepsakes: 3, campVisitor: true }));
await page.waitForTimeout(1800);
await page.screenshot({ path: 'scripts/art/evidence/island-open.png' });
metrics.open = await page.evaluate(() => window.artInfo);
await page.evaluate(() => {
  window.setArtState({ ferryProgress: .5, rescued: true, keepsakes:[false,true,false], transport: { from:'west', to:'east', phase:'sailing', progress:.5, empty:false } });
  window.setArtCamera('ferry');
});
await page.waitForTimeout(400);
await page.screenshot({ path: 'scripts/art/evidence/ferry-sailing.png' });
metrics.sailing = await page.evaluate(() => window.artInfo);
await page.evaluate(() => window.setArtState({ transport: { from:'east', to:'west', phase:'sailing', progress:.5, empty:false } }));
await page.waitForTimeout(400);
await page.screenshot({ path: 'scripts/art/evidence/ferry-return.png' });
await page.evaluate(() => window.setArtState({ ferryProgress: 1, ferrySide: 'east', transport: null }));
await page.waitForTimeout(400);
await page.screenshot({ path: 'scripts/art/evidence/ferry-east.png' });
metrics.east = await page.evaluate(() => window.artInfo);
await writeFile('scripts/art/evidence/two-ways-art-report.json', JSON.stringify({ errors, metrics }, null, 2) + '\n');
console.log(JSON.stringify({ errors, metrics }, null, 2));
await browser.close();
