import { chromium } from 'playwright';
import fs from 'node:fs/promises';
await fs.mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
page.on('pageerror', e => console.log('PAGEERROR', e.message));
page.on('console', m => { if (m.type() === 'error') console.log('CONSOLE', m.text()); });
await page.goto(process.env.GAME_URL || 'http://127.0.0.1:5189/');
await page.waitForFunction(() => window.__RESCUE__?.snapshot().loaded, { timeout: 60000 });
await page.getByRole('button', { name: "Let's go!" }).waitFor();
await page.waitForTimeout(1200);
await page.screenshot({ path: 'artifacts/intro-desktop.png' });
console.log(JSON.stringify(await page.evaluate(() => window.__RESCUE__.diagnostics())));
await page.getByRole('button', { name: "Let's go!" }).click();
await page.waitForTimeout(1200);
await page.screenshot({ path: 'artifacts/gameplay-desktop.png' });
console.log(JSON.stringify(await page.evaluate(() => window.__RESCUE__.snapshot())));
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(2000);
await page.screenshot({ path: 'artifacts/gameplay-mobile.png' });
await browser.close();
